# Generated by Django 5.1.1 on 2024-12-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_account_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_holder',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='account_holder',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='account_holder',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account_holder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='account_holder',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='account_holder',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account_holder',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account_holder',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='office_employee',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
