# Generated by Django 5.1.1 on 2024-12-20 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_account_holder_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_holder',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.office_employee'),
        ),
    ]
