# Generated by Django 5.1.1 on 2024-12-20 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_account_holder_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='saving_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_amount', models.FloatField(null=True)),
                ('debit_amount', models.FloatField(null=True)),
                ('remark', models.CharField(default='', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('account_holder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.account_holder')),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.office_employee')),
            ],
        ),
    ]
