# Generated by Django 5.1.4 on 2024-12-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_saving_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving_account',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
