# Generated by Django 5.1.1 on 2024-12-21 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_account_type_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving_account',
            name='account_holder',
        ),
        migrations.RemoveField(
            model_name='saving_account',
            name='collected_by',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='status',
        ),
        migrations.AddField(
            model_name='account',
            name='collected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.office_employee'),
        ),
        migrations.AddField(
            model_name='account',
            name='credit_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='debit_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='remark',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='saving_account',
        ),
    ]
